---
title: "Revision GPE2"
output: html_notebook
---
# data loading
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE,echo = FALSE,warning = FALSE, message=FALSE)

library(tidyverse)
library(readxl)
library(readr)
library(shadowtext)
library(ggrepel)
library('bbplot')
library(waterfalls)
library(directlabels)
library(forcats)

SAVE_ici<-FALSE
```

```{r import data}
#result<-read.csv('data/result.csv',sep = "\t")

result<-read.csv('data/match_40/results_match_40_multiplicatif.csv',sep = ",") %>% 
  mutate('match'="match_40")

for (namei in c("match_20","match_60","no_match_40")){
tmp<-read.csv(paste0('data/',namei,'/results_',namei,'_multiplicatif.csv'),sep = ",") %>% 
  mutate('match'=namei)
result<-rbind(result, tmp)
}

result<-result %>% 
  pivot_longer(2:5,names_to="group")%>% 
  mutate(group=case_when(
    group=='group2' ~ "Group 1\n(high income)",
    group=='group3' ~ "Group 2\n(middle income)",
    group=='group4' ~ "Group 3\n(low income)",
    group=='group5' ~ "Group 4\n(low income)"
  ))

result2<-result%>% 
  mutate(year=str_wrap(year,width=6))

#weighted_accessibility<-read.csv('data/weighted_accessibility.csv',sep = "\t")
weighted_accessibility<-read.csv('data/match_40/weighted_accessibility_match_40.csv',sep = ",") %>% 
  rename('year'='X') %>% 
  pivot_longer(cols=-1,names_to = 'group') %>% 
  mutate(group=case_when(
    group=='group2' ~ "Group 1\n(high income)",
    group=='group3' ~ "Group 2\n(middle income)",
    group=='group4' ~ "Group 3\n(low income)",
    group=='group5' ~ "Group 4\n(low income)"
  ))

# add 'Real accessibility gains (%)'
result <- result %>% 
  select(-X) %>% 
  pivot_wider(names_from = name,values_from = value) %>% 
  mutate(`Real accessibility gains (%)`= 100*(1+`Job growth (%)`/100)*(1+`Speed (%)`/100)*(1+`Proximity (%)`/100)-100) %>% 
  rename('Proximity - households (%)'='Proximity - hh (%)') %>% 
  pivot_longer(-c(year,match,group)) 


pop_revision <- read.csv('Revisions/detail_par_commune/pop_par_commune.csv',sep = ",") %>%
  select(-seq(3,9)) %>% 
  pivot_longer(cols=-c(seq(1,3)),names_to = "group",)

result_revision <- read.csv('Revisions/detail_par_commune/weighted_accessibility_40_matching.csv',sep = ",") %>% 
  left_join(pop_revision,by = c("COD_ORIG"="CODGEO", "year","group"))
  
temp <- result_revision %>% 
  ungroup() %>% 
  group_by(group,year)%>% 
  summarise(pop_tot=sum(value/1000,na.rm = TRUE),
            mpg = sum(t1/t0*value/1000,na.rm = TRUE)/pop_tot)


```

### par commune 1968
```{r par commune}
#for (nami in c('Job growth (%)','Real accessibility gains (%)','Speed (%)','Proximity (%)',"Proximity - households (%)","Proximity - jobs (%)")){
nami='Real accessibility gains (%)'
p<-result_revision %>% 
  filter(
         year=="1990"
         ) %>% 
ggplot(aes(x=group,y=t2/t1,color=group))+
  geom_jitter(alpha=0.05,stat="identity")+
  geom_boxplot()+
  bbc_style()+
  #facet_wrap('name',scales='free')+
  theme(legend.position = "top", 
        legend.justification = "left",
        axis.ticks.x = element_line(colour = "#333333"), 
        axis.ticks.length =  unit(0.26, "cm")) +
  theme(
    legend.title = element_blank(),
    # panel.border = element_blank(),
    # panel.background = element_blank(),
    # strip.background = element_blank(),
  )+
  geom_hline(yintercept = 0000000, size = 1, colour="#333333") +
  labs(subtitle = "Difference in accessibility in each time period (%)",title="Accessibility variations")

if (SAVE_ici) {
ggsave(paste0("./outputs/bars_Total.png"),plot=p,
       width = 2666/300,
       height= 1875/300,
       unit="in")
}

plot(p)
#}
```


### accessibilite totale variation 1968-1975
```{r bars all accessibility}
#for (nami in c('Job growth (%)','Real accessibility gains (%)','Speed (%)','Proximity (%)',"Proximity - households (%)","Proximity - jobs (%)")){
nami='Real accessibility gains (%)'
p<-result %>% 
  filter(match=='match_40',
         name==nami,
         year=="1968-1975"
         ) %>% 
ggplot(aes(x=year,y=value))+
  geom_bar(stat="identity", position=position_dodge(), aes(fill=group),show.legend = TRUE,width=0.6)+
  bbc_style()+
  #facet_wrap('name',scales='free')+
  theme(legend.position = "top", 
        legend.justification = "left",
        axis.ticks.x = element_line(colour = "#333333"), 
        axis.ticks.length =  unit(0.26, "cm")) +
  theme(
    legend.title = element_blank(),
    # panel.border = element_blank(),
    # panel.background = element_blank(),
    # strip.background = element_blank(),
  )+
  geom_hline(yintercept = 0000000, size = 1, colour="#333333") +
  labs(subtitle = "Difference in accessibility in each time period (%)",title="Accessibility variations")

if (SAVE_ici) {
ggsave(paste0("./outputs/bars_Total.png"),plot=p,
       width = 2666/300,
       height= 1875/300,
       unit="in")
}

plot(p)
#}
```