---
title: "maps"
format: html
editor: visual
---


```{r}
library(tidyverse)
library(ncdf4)
library(stars)   
library(purrr)
library(dplyr)
library(readxl)
library(arrow)
library(ggspatial)
library(scales)

# install.packages('devtools')
#devtools::install_github('bbc/bbplot')
library('bbplot')
```
# load data
```{r}
final_data <- read_parquet("./data/final_data.parquet")
```

# maps data

```{r}
shapefile_init <- st_read("./data/Communes/COMMUNE_SPF.shp") 
st_crs(shapefile_init) <- 3857


shapefile <- shapefile_init%>%
  filter(INSEE_REG == "11") %>%
  st_transform(4326)
```

# plot map temperature 

## 2019
```{r}


tmp <- NFR010C %>% 
  mutate(year = year(date),
         month = month (date)) %>%
  filter(year %in% c(2019),
         month %in% c(6,7,8)) %>% 
  group_by(COM) %>% 
  summarise(tn = mean(tn))

tmp2 <- shapefile %>% 
  mutate(COM = as.double(INSEE_COM)) %>% 
  dplyr::select (c(COM,geometry)) %>% 
  left_join(tmp,by =c("COM" = "COM") )
  
p <- tmp2 %>%  ggplot()+
  geom_sf(aes(fill = tn),color="grey50",size=.2)+
  #geom_sf(aes(fill = tn),lwd=0)+
  scale_fill_viridis_c()+
  bbc_style()+
  annotation_scale(location = "bl", width_hint = 0.25) +
  annotation_north_arrow(location = "br", which_north = "true", 
                         #pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "right")+
  ggtitle("Summer minimal temperature (°C)\nin Île de France",subtitle = "Average for JJA 2019")

ggsave(paste0("./outputs/map_2019_night_JJA.png"),plot=p,
       width = 2666/280,
       height= 1875/280,
       unit="in")

```
## temp diff in 2019 land use

```{r}


tmp_C <- NFR010C %>% 
  mutate(year = year(date),
         month = month (date)) %>%
  filter(year %in% c(2019),
         month %in% c(6,7,8)) %>% 
  group_by(COM) %>% 
  summarise(tn = mean(tn))

tmp_D <- NFR010D %>% 
  mutate(year = year(date),
         month = month (date)) %>%
  filter(year %in% c(2019),
         month %in% c(6,7,8)) %>% 
  group_by(COM) %>% 
  summarise(tn = mean(tn))

tmp <- tmp_C %>% 
  rename("tn_C" = "tn") %>% 
  left_join(tmp_D) %>% 
   rename("tn_D" = "tn") %>% 
  mutate(tmp_diff = tn_D-tn_C)

tmp2 <- shapefile %>% 
  mutate(COM = as.double(INSEE_COM)) %>% 
  dplyr::select (c(COM,geometry)) %>% 
  left_join(tmp,by =c("COM" = "COM") )
  
p <- tmp2 %>%  ggplot()+
  geom_sf(aes(fill = tmp_diff),color="grey50",size=.2)+
  #geom_sf(aes(fill = tn),lwd=0)+
  scale_fill_viridis_c()+
  bbc_style()+
  annotation_scale(location = "bl", width_hint = 0.25) +
  annotation_north_arrow(location = "br", which_north = "true", 
                         #pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "right")+
  ggtitle("Impact of land-use change (1990 - 2018)\non air temperature",subtitle = "simulated temperature difference (°C) for JJA 2019")

ggsave(paste0("./outputs/map_diff_2019_night_JJA.png"),plot=p,
       width = 2666/280,
       height= 1875/280,
       unit="in")

p
```

# map population

## absolute

```{r}

tmp <- final_data %>% 
  filter(year %in% c(2019))

tmp2 <- shapefile %>% 
  dplyr::select (c(INSEE_COM,geometry)) %>% 
  left_join(tmp,by =c("INSEE_COM" = "INSEE_COM") )
  
p <- tmp2 %>%  ggplot()+
  geom_sf(aes(fill = `65+_90`),color="grey50",size=.2)+
    scale_fill_viridis_c(trans = log_trans(),
                     # This breaks_log() thing happens behind the scenes and
                     # isn't strictly necessary here
                      breaks = breaks_log(base =10),
                     #labels = label_math(e^.x, format = log)
                     )+
  #geom_sf(aes(fill = tn),lwd=0)+
  bbc_style()+
  annotation_scale(location = "bl", width_hint = 0.25) +
  annotation_north_arrow(location = "br", which_north = "true", 
                         #pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "right")+
  ggtitle("Population aged 65+ in each Commune",subtitle = "1990")

p
ggsave(paste0("./outputs/map_population_65_1990.png"),plot=p,
       width = 2666/280,
       height= 1875/280,
       unit="in")

p <- tmp2 %>%  
  dplyr::select(geometry,`65+_90`,`65+_18`) %>% 
  pivot_longer(-c(geometry)) %>% 
  mutate(name = case_when(
    name == "65+_90" ~1990,
    name == "65+_18" ~2018
  )) %>% 
  ggplot()+
  geom_sf(aes(fill = value),color="grey50",size=.2)+
    scale_fill_viridis_c(trans = log_trans(),
                     # This breaks_log() thing happens behind the scenes and
                     # isn't strictly necessary here
                      breaks = breaks_log(base =10),
                     #labels = label_math(e^.x, format = log)
                     )+
  #geom_sf(aes(fill = tn),lwd=0)+
  facet_wrap(~name)+
  bbc_style()+
  annotation_scale(location = "bl", width_hint = 0.25) +
  # annotation_north_arrow(location = "br", which_north = "true", 
  #                        #pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
  #                        style = north_arrow_fancy_orienteering,
  #                        height = unit(.5, "cm"),
  #                        width = unit(.5, "cm")) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "right")+
  ggtitle("Population aged 65+ in each Commune")

p
ggsave(paste0("./outputs/map_population_65.png"),plot=p,
       width = 2666/280*1.5,
       height= 1875/280,
       unit="in")
```
## difference

```{r}

tmp <- final_data %>% 
  filter(year %in% c(2019))

tmp2 <- shapefile %>% 
  dplyr::select (c(INSEE_COM,geometry)) %>% 
  left_join(tmp,by =c("INSEE_COM" = "INSEE_COM") ) %>% 
  mutate(diff= (`65+_18` - `65+_90`))
  
#st_write(tmp2, "commune_pour_carte.shp")


p <- tmp2 %>% 
  ggplot()+
  geom_sf(aes(fill = diff),color="grey50",size=.2)+
  scale_fill_distiller(palette = "PuOr",
                       #limits = c(-max(abs(tmp2$diff)),max(abs(tmp2$diff))),
                       limits = c(-10000,10000),
                       breaks = c(-10000,-5000,0,5000,10000))+
  #geom_sf(aes(fill = tn),lwd=0)+
  bbc_style()+
  annotation_scale(location = "bl", width_hint = 0.25) +
  annotation_north_arrow(location = "br", which_north = "true", 
                         #pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "right")+
  ggtitle("Variation in population aged 65+ in each Commune",subtitle = "Evolution between 1990 and 2018")

p

ggsave(paste0("./outputs/map_population_65_evolution.png"),plot=p,
       width = 2666/280*1.5,
       height= 1875/280,
       unit="in")
```

